### ISSUE TITLE
error 2013 (Lost connection to MySQL server during query)

### ISSUE THREAD

**Issue by minxinqing** [nooncall/shazam#50]
用sysbench压测，显示以下错误：
```
FATAL: mysql_drv_query() returned error 2013 (Lost connection to MySQL server during query) for query 'SELECT DISTINCT c FROM sbtest1 WHERE id BETWEEN 591520 AND 591619 ORDER BY c'
FATAL: mysql_drv_query() returned error 2013 (Lost connection to MySQL server during query) for query 'COMMIT'
FATAL: `thread_run' function failed: /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua:110: db_query() failed
FATAL: `thread_run' function failed: /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua:69: db_query() failed
```

proxy崩溃，输出以下日志：
```
panic: StartEphemeralPacket cannot be used while a packet is already started.

goroutine 216 [running]:
github.com/nooncall/shazam/mysql.(*Conn).StartEphemeralPacket(...)
	/Users/minxinqing/workspace/code/go/src/github.com/nooncall/shazam/mysql/conn.go:442
github.com/nooncall/shazam/backend.(*DirectConnection).writeComQuery(0xc0009389c0, 0xe57e77, 0x8, 0xc0002f4ee0, 0xc00014e098)
	/Users/minxinqing/workspace/code/go/src/github.com/nooncall/shazam/backend/direct_connection.go:327 +0x152
github.com/nooncall/shazam/backend.(*DirectConnection).exec(0xc0009389c0, 0xe57e77, 0x8, 0x0, 0x0, 0x0)
	/Users/minxinqing/workspace/code/go/src/github.com/nooncall/shazam/backend/direct_connection.go:563 +0x43
github.com/nooncall/shazam/backend.(*DirectConnection).Rollback(...)
	/Users/minxinqing/workspace/code/go/src/github.com/nooncall/shazam/backend/direct_connection.go:425
github.com/nooncall/shazam/backend.(*PooledConnection).Rollback(...)
	/Users/minxinqing/workspace/code/go/src/github.com/nooncall/shazam/backend/pooled_connection.go:88
github.com/nooncall/shazam/proxy/server.(*SessionExecutor).rollback(0xc00030a240, 0xcd52c0, 0x157a0c1)
	/Users/minxinqing/workspace/code/go/src/github.com/nooncall/shazam/proxy/server/executor.go:653 +0xbb
github.com/nooncall/shazam/proxy/server.(*Session).Close(0xc0003fe370)
	/Users/minxinqing/workspace/code/go/src/github.com/nooncall/shazam/proxy/server/session.go:192 +0xa8
created by github.com/nooncall/shazam/util.(*TimeWheel).handleTick
	/Users/minxinqing/workspace/code/go/src/github.com/nooncall/shazam/util/time_wheel.go:104 +0x19d
```

各项timeout参数如下：
mysql wait_timeout=86400
proxy session_timeout=60
namespace  idle_timeout=50

sysbench压测120秒

**Comment by chicliz** [comment]
试试把这行移除？目前看应该是重复添加了 
s.tw.Add(s.sessionTimeout, cc, cc.Close)
proxy/server/server.go: 137

**Comment by minxinqing** [comment]
我试试

**Comment by teckick** [comment]
https://github.com/nooncall/shazam/blob/a3b679f830a6d82740b4040c30cb873bf3be9fb2/proxy/server/executor.go#L56

这里应该要加锁

**Comment by teckick** [comment]
@minxinqing 最新版本已经修复了这个bug, 您在压测时还有遇到这个问题吗?

**Comment by minxinqing** [comment]
没这个问题了，我关了吧
